-- Reglement fournisseurs (UX-04) : on savait ce qu'un fournisseur avait facture, jamais si on
-- l'avait paye. La question "combien je dois, et a qui" etait sans reponse, ce qui est la
-- moitie manquante de la tresorerie.
--
-- Comme pour l'echeancier, l'etat n'est pas stocke : il se deduit de la somme des reglements
-- rapportee au TTC de la facture, et de l'echeance quand elle est renseignee.
CREATE TABLE supplier_payments
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMP        NOT NULL,
    updated_at     TIMESTAMP        NOT NULL,
    version        BIGINT DEFAULT 0 NOT NULL,
    invoice_id     BIGINT           NOT NULL,
    payment_date   DATE             NOT NULL,
    amount         NUMERIC(19, 3)   NOT NULL,
    payment_method VARCHAR(40),
    reference      VARCHAR(120),
    notes          VARCHAR(1000),
    CONSTRAINT fk_supplier_payments_invoice FOREIGN KEY (invoice_id)
        REFERENCES supplier_invoices (id) ON DELETE CASCADE
);

CREATE INDEX idx_supplier_payments_invoice ON supplier_payments (invoice_id);
CREATE INDEX idx_supplier_payments_date ON supplier_payments (payment_date);

-- Date d'echeance de la facture : sans elle on ne peut pas dire ce qui est en retard.
ALTER TABLE supplier_invoices
    ADD COLUMN due_date DATE;
