-- Baseline du schema SPI Ghomrassen, derive des classes @Entity de com.promoteur.app.entity.
-- Toute colonne monetaire est NUMERIC(19,3) : le dinar tunisien se compte en millimes.
-- Script volontairement portable PostgreSQL / H2 : le profil test rejoue les memes migrations.

CREATE TABLE projects
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        TIMESTAMP    NOT NULL,
    updated_at        TIMESTAMP    NOT NULL,
    code              VARCHAR(255) NOT NULL,
    name              VARCHAR(255) NOT NULL,
    location          VARCHAR(255),
    description       VARCHAR(1000),
    start_date        DATE,
    expected_end_date DATE,
    budget            NUMERIC(19, 3),
    status            VARCHAR(255),
    active_context    BOOLEAN,
    CONSTRAINT uk_projects_code UNIQUE (code)
);

CREATE TABLE clients
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       TIMESTAMP    NOT NULL,
    updated_at       TIMESTAMP    NOT NULL,
    full_name        VARCHAR(255) NOT NULL,
    phone            VARCHAR(255),
    email            VARCHAR(255),
    address          VARCHAR(255),
    cin_or_fiscal_id VARCHAR(255),
    notes            VARCHAR(1000),
    active           BOOLEAN,
    project_id       BIGINT,
    CONSTRAINT fk_clients_project FOREIGN KEY (project_id) REFERENCES projects (id)
);

CREATE TABLE apartments
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       TIMESTAMP      NOT NULL,
    updated_at       TIMESTAMP      NOT NULL,
    apartment_number VARCHAR(255)   NOT NULL,
    apartment_type   VARCHAR(255)   NOT NULL,
    total_surface    NUMERIC(19, 3) NOT NULL,
    garden_surface   NUMERIC(19, 3),
    parking_count    VARCHAR(255),
    cellar_count     INTEGER,
    total_sale_price NUMERIC(19, 3),
    detail           VARCHAR(2000),
    project_id       BIGINT         NOT NULL,
    client_id        BIGINT,
    CONSTRAINT fk_apartments_project FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_apartments_acquirer FOREIGN KEY (client_id) REFERENCES clients (id)
);

CREATE TABLE expense_categories
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    name       VARCHAR(255) NOT NULL
);

CREATE TABLE supplier_type_options
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    label      VARCHAR(255) NOT NULL,
    active     BOOLEAN,
    CONSTRAINT uk_supplier_type_options_label UNIQUE (label)
);

CREATE TABLE suppliers
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    name       VARCHAR(255) NOT NULL,
    fiscal_id  VARCHAR(255),
    phone      VARCHAR(255),
    email      VARCHAR(255),
    address    VARCHAR(255),
    active     BOOLEAN,
    type_id    BIGINT,
    CONSTRAINT fk_suppliers_type FOREIGN KEY (type_id) REFERENCES supplier_type_options (id)
);

CREATE TABLE client_purchases
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        TIMESTAMP      NOT NULL,
    updated_at        TIMESTAMP      NOT NULL,
    reference         VARCHAR(255)   NOT NULL,
    purchase_date     DATE           NOT NULL,
    contract_date     DATE,
    asset_description VARCHAR(255)   NOT NULL,
    total_amount      NUMERIC(19, 3) NOT NULL,
    paid_amount       NUMERIC(19, 3) NOT NULL,
    attachment_name   VARCHAR(255),
    attachment_url    VARCHAR(255),
    notes             VARCHAR(1000),
    client_id         BIGINT         NOT NULL,
    project_id        BIGINT         NOT NULL,
    apartment_id      BIGINT         NOT NULL,
    CONSTRAINT uk_client_purchases_reference UNIQUE (reference),
    -- Un appartement ne peut faire l'objet que d'un seul contrat de vente.
    CONSTRAINT uk_client_purchases_apartment UNIQUE (apartment_id),
    CONSTRAINT fk_client_purchases_client FOREIGN KEY (client_id) REFERENCES clients (id),
    CONSTRAINT fk_client_purchases_project FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_client_purchases_apartment FOREIGN KEY (apartment_id) REFERENCES apartments (id)
);

CREATE TABLE client_advances
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP      NOT NULL,
    updated_at      TIMESTAMP      NOT NULL,
    reference       VARCHAR(255)   NOT NULL,
    advance_date    DATE           NOT NULL,
    amount          NUMERIC(19, 3) NOT NULL,
    payment_method  VARCHAR(255),
    attachment_name VARCHAR(255),
    attachment_url  VARCHAR(255),
    notes           VARCHAR(1000),
    client_id       BIGINT         NOT NULL,
    project_id      BIGINT         NOT NULL,
    apartment_id    BIGINT         NOT NULL,
    CONSTRAINT uk_client_advances_reference UNIQUE (reference),
    CONSTRAINT fk_client_advances_client FOREIGN KEY (client_id) REFERENCES clients (id),
    CONSTRAINT fk_client_advances_project FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_client_advances_apartment FOREIGN KEY (apartment_id) REFERENCES apartments (id)
);

CREATE TABLE expenses
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP      NOT NULL,
    updated_at      TIMESTAMP      NOT NULL,
    reference       VARCHAR(255)   NOT NULL,
    expense_date    DATE           NOT NULL,
    description     VARCHAR(255)   NOT NULL,
    amount_ht       NUMERIC(19, 3) NOT NULL,
    vat_amount      NUMERIC(19, 3),
    amount_ttc      NUMERIC(19, 3) NOT NULL,
    payment_method  VARCHAR(255),
    document_number VARCHAR(255),
    attachment_name VARCHAR(255),
    attachment_url  VARCHAR(255),
    notes           VARCHAR(1000),
    category_id     BIGINT         NOT NULL,
    project_id      BIGINT         NOT NULL,
    supplier_id     BIGINT,
    CONSTRAINT uk_expenses_reference UNIQUE (reference),
    CONSTRAINT fk_expenses_category FOREIGN KEY (category_id) REFERENCES expense_categories (id),
    CONSTRAINT fk_expenses_project FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_expenses_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id)
);

CREATE TABLE supplier_invoices
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at         TIMESTAMP      NOT NULL,
    updated_at         TIMESTAMP      NOT NULL,
    invoice_number     VARCHAR(255)   NOT NULL,
    invoice_date       DATE           NOT NULL,
    amount_ht          NUMERIC(19, 3) NOT NULL,
    vat_amount         NUMERIC(19, 3) NOT NULL,
    amount_ttc         NUMERIC(19, 3) NOT NULL,
    withholding_amount NUMERIC(19, 3) NOT NULL,
    net_to_pay         NUMERIC(19, 3) NOT NULL,
    attachment_name    VARCHAR(255),
    attachment_url     VARCHAR(255),
    detail             VARCHAR(2000),
    supplier_id        BIGINT         NOT NULL,
    project_id         BIGINT         NOT NULL,
    CONSTRAINT uk_supplier_invoices_invoice_number UNIQUE (invoice_number),
    CONSTRAINT fk_supplier_invoices_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id),
    CONSTRAINT fk_supplier_invoices_project FOREIGN KEY (project_id) REFERENCES projects (id)
);

CREATE TABLE audit_logs
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP     NOT NULL,
    updated_at  TIMESTAMP     NOT NULL,
    entity_type VARCHAR(255)  NOT NULL,
    entity_id   BIGINT        NOT NULL,
    action      VARCHAR(255)  NOT NULL,
    summary     VARCHAR(1000) NOT NULL
);

-- Index sur chaque colonne de cle etrangere.
-- client_purchases.apartment_id est deja indexe par uk_client_purchases_apartment.
CREATE INDEX idx_clients_project ON clients (project_id);
CREATE INDEX idx_apartments_project ON apartments (project_id);
CREATE INDEX idx_apartments_client ON apartments (client_id);
CREATE INDEX idx_suppliers_type ON suppliers (type_id);
CREATE INDEX idx_client_purchases_client ON client_purchases (client_id);
CREATE INDEX idx_client_purchases_project ON client_purchases (project_id);
CREATE INDEX idx_client_advances_client ON client_advances (client_id);
CREATE INDEX idx_client_advances_project ON client_advances (project_id);
CREATE INDEX idx_client_advances_apartment ON client_advances (apartment_id);
CREATE INDEX idx_expenses_category ON expenses (category_id);
CREATE INDEX idx_expenses_project ON expenses (project_id);
CREATE INDEX idx_expenses_supplier ON expenses (supplier_id);
CREATE INDEX idx_supplier_invoices_supplier ON supplier_invoices (supplier_id);
CREATE INDEX idx_supplier_invoices_project ON supplier_invoices (project_id);

-- Index sur les colonnes de date interrogees par les rapports periodiques.
CREATE INDEX idx_expenses_expense_date ON expenses (expense_date);
CREATE INDEX idx_client_advances_advance_date ON client_advances (advance_date);
CREATE INDEX idx_client_purchases_purchase_date ON client_purchases (purchase_date);
