-- CALC-01 : le taux de TVA etait fige a 19 % dans le navigateur. La Tunisie applique 0 %,
-- 7 %, 13 % et 19 % ; le taux devient une donnee portee par chaque piece, et le backend
-- devient la seule source de verite du calcul.

CREATE TABLE vat_rate_options
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP     NOT NULL,
    updated_at TIMESTAMP     NOT NULL,
    label      VARCHAR(255)  NOT NULL,
    rate       NUMERIC(5, 4) NOT NULL,
    active     BOOLEAN,
    CONSTRAINT uk_vat_rate_options_rate UNIQUE (rate)
);

ALTER TABLE expenses
    ADD COLUMN vat_rate NUMERIC(5, 4);
UPDATE expenses
SET vat_rate = 0.1900
WHERE vat_rate IS NULL;
ALTER TABLE expenses
    ALTER COLUMN vat_rate SET NOT NULL;

ALTER TABLE supplier_invoices
    ADD COLUMN vat_rate NUMERIC(5, 4);
UPDATE supplier_invoices
SET vat_rate = 0.1900
WHERE vat_rate IS NULL;
ALTER TABLE supplier_invoices
    ALTER COLUMN vat_rate SET NOT NULL;

-- Taux habituel du fournisseur, propose par defaut a la saisie. Facultatif.
ALTER TABLE suppliers
    ADD COLUMN default_vat_rate NUMERIC(5, 4);
