-- FE-05 : attachment_name / attachment_url etaient de simples champs texte, sans upload, sans
-- stockage, sans fichier servi. Pour un promoteur la preuve EST la piece : bordereau de
-- virement, scan de cheque, page de contrat signee. Le fichier devient une entite, rattachee a
-- son document par (owner_type, owner_id).
CREATE TABLE file_attachments
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP        NOT NULL,
    updated_at    TIMESTAMP        NOT NULL,
    version       BIGINT DEFAULT 0 NOT NULL,
    original_name VARCHAR(255)     NOT NULL,
    storage_key   VARCHAR(255)     NOT NULL,
    content_type  VARCHAR(100)     NOT NULL,
    size_bytes    BIGINT           NOT NULL,
    uploaded_by   VARCHAR(255)     NOT NULL,
    uploaded_at   TIMESTAMP        NOT NULL,
    owner_type    VARCHAR(40)      NOT NULL,
    owner_id      BIGINT           NOT NULL,
    CONSTRAINT uk_file_attachments_storage_key UNIQUE (storage_key)
);

CREATE INDEX idx_file_attachments_owner ON file_attachments (owner_type, owner_id);
