-- Echeancier (UX-03) : la vente sur plan se paie par tranches (reservation, tranches de
-- construction, solde a la livraison). Le contrat ne portait qu'un total, les encaissements
-- etaient enregistres sans plan attendu. Impossible de repondre aux deux questions du matin :
-- qui doit payer ce mois-ci, et qui est en retard.
--
-- Le statut d'une echeance n'est pas stocke : il se deduit de la date d'echeance et de ce qui a
-- ete encaisse sur le contrat, reparti sur les echeances dans l'ordre. Rien a resynchroniser.
CREATE TABLE payment_installments
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP        NOT NULL,
    updated_at  TIMESTAMP        NOT NULL,
    version     BIGINT DEFAULT 0 NOT NULL,
    purchase_id BIGINT           NOT NULL,
    sequence_no INTEGER          NOT NULL,
    label       VARCHAR(120)     NOT NULL,
    due_date    DATE             NOT NULL,
    amount      NUMERIC(19, 3)   NOT NULL,
    notes       VARCHAR(1000),
    CONSTRAINT uk_payment_installments_sequence UNIQUE (purchase_id, sequence_no),
    CONSTRAINT fk_payment_installments_purchase FOREIGN KEY (purchase_id)
        REFERENCES client_purchases (id) ON DELETE CASCADE
);

CREATE INDEX idx_payment_installments_purchase ON payment_installments (purchase_id);
CREATE INDEX idx_payment_installments_due_date ON payment_installments (due_date);
